<?= tableOpen([
	'주문번호',
	'상품명',
	'모델명',
	'계약 기간',
	'주문자',
	'연락처',
	'주문일',
	'상태'
]) ?>

<?php foreach ($orders as $order): ?>
    <tr>
        <td><?= $order['id'] ?></td>
        <td><?= $order['product_name'] ?></td>
        <td><?= $order['product_model'] ?></td>
        <td><?= $order['term'] ?>개월</td>
        <td><?= $order['name'] ?></td>
        <td><?= $order['phone'] ?></td>
        <td><?= $order['inserted'] ?></td>
        <td><?= $order['stateText'] ?></td>
    </tr>
<?php endforeach ?>
<?= tableClose ?>
