<?php
$required = ['required' => true];
$typeMonth = [
	'type' => 'number',
	'min'  => '0',
];

?>
<?= formOpen('post.php') ?>

<?= h2('기본 설정') ?>

<?= tableOpen() ?>
<?= trInput('name', '카드명', '', $required) ?>
<?= trInput('index', '구분 값', '', $required) ?>
    <tr>
        <th>실적 인정</th>
        <td>
			<?php foreach ($offsetIncludes as $key => $value): ?>
                <label>
                    <input type="checkbox" name="offset" value="1">
					<?= $value ?>
                </label>
			<?php endforeach ?>
        </td>
    </tr>
<?= trInput('grace-period', '실적 유예기간') ?>
<?= trInput('fee-in', '국내 연회비', '', $required) ?>
<?= trInput('fee-out', '해외 연회비', '', $required) ?>

<?= tableClose ?>

<?= h2('렌탈 혜택') ?>
<?= tableOpen([
	'할인 조건(N원 이상 사용)',
	'청구 할인 액',
	'할인 횟수',
	'관리'
]) ?>
<?= tableClose ?>
<?= h2('할부 구매 혜택') ?>
<?= tableOpen([
	'구매 조건(N원 이상 결제)',
	'할부 개월',
	'관리'
]) ?>
<?= tableClose ?>
<?= h2('즉시 구매 혜택') ?>
<?= tableOpen([
	'할인 조건(N원 이상 실적)',
	'할인액',
	'관리'
]) ?>
<?= tableClose ?>
<?= buttonsOpen ?>
<?= buttonLink('index.php', '목록') ?>
<?= buttonSubmit('카드 추가') ?>
<?= buttonsClose ?>
<?= formClose ?>