<?=formOpen('./vendor-action.php')?>
	<?= formTable(
		'운영 정보',
		[
			['company', '회사명'],
			['post', '우편번호'],
			['address', '주소'],
			['owner', '대표'],
			['phone', '전화번호'],
			['fax', '팩스번호'],
			['crn', '사업자 번호'],
			['osdn', '통신 판매업 신고 번호'],
			['subOsdn', '부가 통신 사업자 번호'],
			['infoManager', '정보관리 책임자'],
			['infoManagerEmail', '정보관리 책임자 전자우편']
		]
	) ?>

	<?= formTable(
		'서비스 정보',
		[
			['csNumber', '고객센터 전화번호'],
			['csEmail', '고객센터 전자우편'],
			['smsNumber', '문자 발송 번호'],
			['localSmsNumber', '개발용 문자 발송 번호'],
			['kakaoYellowId', '카카오 옐로우 아이디'],
			['kakaoStory', '카카오 스토리 아이디'],
			['facebook', '페이스북 아이디'],
			['twitter', '트위터 아이디'],
			['instagram', '인스타그램 아이디']
		]
	) ?>
    <?=formSubmitOnly()?>
<?=formClose?>